config/routes.rb
Rails.application.routes.draw do
  resources :sessions
  resources :users
  
  resources :password_resets, only: [ :new, :create]
  
  get '/password_resets/edit' => 'password_resets#edit', as: :edit_password_reset
  put '/password_resets/' => 'password_resets#update', as: :password_reset
  

  root 'welcome#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  
  validates :password, length: { minimum: 5}
  validates :email, uniqueness: true
  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }
  
  def deliver_password_reset_instructions
    save_token
      
    PasswordResetNotifier.password_reset_instructions(self).deliver_now
  end
  
  def save_token
    self.perishable_token = SecureRandom.hex(4)
    save(validate: false)    
  end  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  private
  
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
  helper_method :current_user
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  def new
  end
  
  def create
    user = User.where(email: params[:email]).first
    
    if user
      user.deliver_password_reset_instructions
      flash[:notice] = "Instructions to reset your password have been emailed to you"
      
      redirect_to root_path
    else
      flash.now[:error] = "No user was found with email address #{params[:email]}"
      render :new
    end
  end
  
  def edit
    load_user_using_perishable_token
    @token = @user.perishable_token
  end
  
  def update
    load_user_using_perishable_token
    @user.password = params[:password]

    if @user.save
      # reset token, so that old token expires
      @user.save_token
      flash[:success] = "Your password was successfully updated"
      redirect_to @user
    else
      render :edit
    end
  end
  
  private 
  
  def load_user_using_perishable_token
    @user = User.where(perishable_token: params[:token]).first
    unless @user
      flash[:error] = "We're sorry, but we could not locate your account"
      redirect_to root_url
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: "Logged in!"
    else
      flash.now.alert = "Email or password is invalid."
    end
  end
  
  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: 'Logged out!'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(permitted_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, notice: "Thank you for signing up!"
    else
      render "new"
    end
  end
  
  private
  
  def permitted_params
    params.require(:user).permit(:email, :password)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ascrat</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <% if current_user %>
    Logged in as <%= current_user.email %>.
	<%= link_to "Log Out", session_path("current"), method: "delete" %>
  <% else %>
    <%= link_to "Sign Up", new_user_path %> or
    <%= link_to "Log In", new_session_path %>
  <% end %>
   

  <% flash.each do |name, msg| %>
     <%= content_tag :div, msg, class: "alert alert-info" %>
  <% end %>

<%= yield %>

</body>
</html>

app/views/password_reset_notifier/password_reset_instructions.html.erb
<h1>Password Reset Instructions</h1>

<p>
  A request to reset your password has been made. If you did not make
  this request, simply ignore this email. If you did make this
  request, please click the link below.
</p>

<%= link_to "Reset Password!", @url %>

app/views/password_resets/edit.html.erb
<h1>Update your password</h1>

<p>Please enter the new password below and then press "Update Password".</p>

<%= form_tag password_reset_path, :method => :put do %>
  <%= password_field_tag :password %>
  <%= hidden_field_tag :token, @token %>
  
  <%= submit_tag "Update Password" %>
<% end %>

app/views/password_resets/new.html.erb
<h1>Reset Password</h1>

<p>Please enter your email address below and then press "Reset Password".</p>

<%= form_tag password_resets_path do %>
  <%= text_field_tag :email %>
  <%= submit_tag "Reset Password" %>
<% end %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>

  <div class="actions"><%= f.submit "Signup" %></div>
<% end %>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>